words = [
    "absolutizing",
    "aemo",
    "aest",
    "augroup",
    "autocmds",
    "azs",
    "bashdb",
    "bashls",
    "bigfile",
    "boto",
    "breakpoint",
    "bufhidden",
    "buflisted",
    "bufnr",
    "caddy",
    "caplog",
    "cbfmt",
    "cdk",
    "connectionpoint",
    "containerfile",
    "cov",
    "cron",
    "currentday",
    "dagster",
    "dataframe",
    "dataframes",
    "debugpy",
    "dedupe",
    "deltalake",
    "dfs",
    "dockerfmt",
    "dockerls",
    "dwgm",
    "dwm",
    "ebs",
    "ecgs",
    "ecr",
    "ecs",
    "eip",
    "enew",
    "etl",
    "fargate",
    "fastapi",
    "fck",
    "fixjson",
    "folke",
    "gasbb",
    "gasdate",
    "gbb",
    "gpt",
    "hererocks",
    "iam",
    "jsonls",
    "keymaps",
    "lazyframe",
    "lazypath",
    "lazyrepo",
    "linepack",
    "linters",
    "lnum",
    "localstack",
    "mapleader",
    "maplocalleader",
    "mdformat",
    "mfussenegger",
    "mkfifo",
    "monkeypatch",
    "nargs",
    "nem",
    "nemweb",
    "neovim",
    "nlua",
    "noremap",
    "numhl",
    "nvim",
    "osv",
    "pkill",
    "plh",
    "podman",
    "polars",
    "prek",
    "publicrpts",
    "pyarrow",
    "pyproject",
    "qld",
    "quickfile",
    "rechunk",
    "rpts",
    "sched",
    "shellcheck",
    "shfmt",
    "startinsert",
    "statuscolumn",
    "sttm",
    "stylua",
    "subparsers",
    "swapfile",
    "taplo",
    "texthl",
    "unzipper",
    "unzippper",
    "upserts",
    "utilisation",
    "vicgas",
    "vpc",
    "vscode",
    "workmux",
    "worktree",
    "worktrees",
    "xdist",
    "yamlfmt",
    "yamlls",
    "zuban",
]
ignore_patterns = [
    '\b[ATCG]+\b',
    '\d{3}-\d{2}-\d{4}',
    "^[A-Z]{2,}$",
    'https?://[^\s]+',
    '^\-*',
    '\B-{1,2}[a-zA-Z][\w-]*\b',
]
